#! /bin/bash

# start sxhkd
sxhkd &

# start polybar
~/.config/polybar/launch.sh

# monitors
# m1=$(xrandr --query | grep "DisplayPort" | grep " connected")
# m2=$(xrandr --query | grep "HDMI" | grep " connected")

bspc monitor DisplayPort-0 -d 1 2 3 4 5 6
bspc monitor HDMI-A-0 -d 7 8 9 10

# configuration
bspc config border_width 0
bspc config window_gap 10

bspc config split_ratio 0.5
bspc config focus_follows_pointer true

# set wallpaper
feh --bg-fill --no-fehbg ~/.config/wallpapers/pang-yuhao-7f_DhSd55JY-unsplash.jpg &

# set cursor
xsetroot -cursor_name left_ptr



