#! /bin/bash

bspc monitor DisplayPort-0 -d 1 2 3 4 5 6
bspc monitor HDMI-A-0 -d 7 8 9 10

# configuration
bspc config border_width 4
bspc config window_gap 10
# bspc config top_padding 0

bspc config active_border_color \#24283b
bspc config normal_border_color \#24283b
bspc config focused_border_color \#9ece6a
bspc config split_ratio 0.5
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config pointer_follows_monitor true
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config automatic_scheme longest_first

# set wallpaper
feh --bg-fill --no-fehbg ~/.config/wallpapers/planet-ga638e28ce_1920.jpg &

# start polybar
~/.config/polybar/launch.sh &

# start eww
eww daemon &

# start sxhkd
sxhkd &

# set cursor
xsetroot -cursor_name left_ptr
